In [5]:
#Show me the Money: Forecasting Economic Aid with Machine Learning
#Applied Machine Learning Final Project
#By Majid Khorrami & Laura Kahn
#April 30, 2017
import os
os.getcwd()

'C:\\Users\\lkahn\\Documents\\526-AppliedMachineLearning'

In [1]:
#Import cleaned data manually from CSV
import csv
import pandas as pd
import numpy as np

df = pd.DataFrame()
aid_df = pd.read_csv('aid-cleaned2.csv', index_col=0)
aid_df

2014        2015        2016  \
Country                                                      
Afghanistan             2202642037  2224419103  1263122571   
Albania                   21502503    18553548    11788431   
Algeria                    7494186     7504667     1983881   
Angola                    67107300    61494920    52439601   
Antigua and Barbuda            NaN       14130        3780   
Argentina                  1946256     1825092         NaN   
Armenia                   37272007    39333349    24089150   
Azerbaijan                27489691    22512506    11170994   
Bahamas                    1305824      767064       51562   
Bahrain                     626968     1259711         NaN   
Bangladesh               261713436   250830290   222750371   
Barbados                     69808      208240        4593   
Belarus                   15088903    17390445     8505418   
Belgium                    2100238     5775753         NaN   
Belize                     2289513     1837129      288971   
Benin                     25179853    52991568    33173074   
Bhutan                      327412      780088      291863   
Bolivia                   32976527    59144311       49283   
Bosnia and Herzegovina    48095613    42639175    26187912   
Botswana                  56364651    51461760    12893047   
Brazil                    21781537    19110645     8332332   
Brunei                      243098       94092         NaN   
Bulgaria                   6285952     8614815      263341   
Burkina Faso             228821517    78145904    44402220   
Burma (Myanmar)           90729283   111593470   123248627   
Burundi                   33322571    48383365    42846592   
Cabo Verde                 7743474    11303648     3937068   
Cambodia                  87779748    91597169    74500942   
Cameroon                  38602231    57617656    46325330   
Canada                      373185    47034682         NaN   
...                            ...         ...         ...   
Sri Lanka                 45158210    32631782    23701622   
St. Lucia                     9405       15584         NaN   
Sudan                    262896407   118087120   105005990   
Sudan (former)           145676552   119947915   101546679   
Swaziland                 43950014    34323036    32151297   
Switzerland                 557392     1133352         NaN   
Syria                    786441452   737264094   569845235   
Tajikistan                42683025    35400319    23697925   
Tanzania                 594109297   457116160   297048782   
Thailand                  51942275    53828345     2955684   
Timor-Leste               34253928    21638648    20449989   
Togo                       3162157     3002098      722260   
Tonga                      1334477     1359430      604482   
Trinidad and Tobago         431679      800944         NaN   
Tunisia                   22903789    19506580    18005091   
Turkey                    72542581    41572708      606586   
Turkmenistan               8987261     8337095     2659927   
Uganda                   481777507   404173403   342007462   
Ukraine                  171042405   290271722   136242618   
United Arab Emirates        681233      601655         NaN   
United Kingdom               68416      203479         NaN   
Uruguay                     496200      637682       50000   
Uzbekistan                24585648    15861147     8047023   
Vanuatu                    3042039     4599720     1728323   
Venezuela                  6153088     7287486     5068589   
Vietnam                  109160418    92345258    68299531   
West Bank/Gaza           387347218   456553887   283919737   
Yemen                    220475319   157739743   238518386   
Zambia                   338378808   287497830   185153148   
Zimbabwe                 184794038         NaN   156358791   

                        WB2015GDPGrowthAnnualPCT  
Country                                           
Afghanistan          

In [2]:
print (aid_df [:1])

#Data Pre-processing
#if 2014 is finite (not null), select it. Otherwise drop it. then do the same for other columns
aid_df = aid_df[np.isfinite(aid_df['2014'])]
aid_df = aid_df[np.isfinite(aid_df['2015'])]
aid_df = aid_df[np.isfinite(aid_df['2016'])]
# Please note the slightly renamed column:  WB2015GDPGrowthAnnualPCT
aid_df = aid_df[np.isfinite(aid_df['WB2015GDPGrowthAnnualPCT'])]
print ('*'*5)
print (aid_df.shape)
print ('*'*5)
print (aid_df)

                   2014        2015        2016  WB2015GDPGrowthAnnualPCT
Country                                                                  
Afghanistan  2202642037  2224419103  1263122571                   -1.9466
*****
(135, 4)
*****
                                2014        2015        2016  \
Country                                                        
Afghanistan               2202642037  2224419103  1263122571   
Albania                     21502503    18553548    11788431   
Algeria                      7494186     7504667     1983881   
Angola                      67107300    61494920    52439601   
Armenia                     37272007    39333349    24089150   
Azerbaijan                  27489691    22512506    11170994   
Bahamas                      1305824      767064       51562   
Bangladesh                 261713436   250830290   222750371   
Barbados                       69808      208240        4593   
Belarus                     15088903    17390445     

In [6]:
#Let's take a look at the data
import scipy.stats as stats
aid_df.describe()
#Notice, the standard deviation is a bit higher, which may affect the machine learning classifier.

2014          2015          2016  WB2015GDPGrowthAnnualPCT
count  1.350000e+02  1.350000e+02  1.350000e+02                135.000000
mean   1.314789e+08  1.379006e+08  9.006506e+07                  2.630450
std    2.497316e+08  2.666962e+08  1.667678e+08                  4.772555
min    3.098000e+03  1.439800e+04 -1.088240e+05                -28.096800
25%    7.249812e+06  8.346110e+06  1.434274e+06                  1.282350
50%    4.079492e+07  3.933335e+07  2.044999e+07                  3.227800
75%    1.382383e+08  1.311833e+08  1.206091e+08                  4.948900
max    2.202642e+09  2.224419e+09  1.263123e+09                 12.393200

In [3]:
# convert the data frame, aid_df to matrix. Save it as 'aid'
aid = aid_df.as_matrix(columns=None)
print(aid.shape)
print (aid)

(135, 4)
[[  2.20264204e+09   2.22441910e+09   1.26312257e+09  -1.94660000e+00]
 [  2.15025030e+07   1.85535480e+07   1.17884310e+07   2.95970000e+00]
 [  7.49418600e+06   7.50466700e+06   1.98388100e+06   3.90000000e+00]
 [  6.71073000e+07   6.14949200e+07   5.24396010e+07   3.00700000e+00]
 [  3.72720070e+07   3.93333490e+07   2.40891500e+07   3.00000000e+00]
 [  2.74896910e+07   2.25125060e+07   1.11709940e+07   1.10000000e+00]
 [  1.30582400e+06   7.67064000e+05   5.15620000e+04  -1.66360000e+00]
 [  2.61713436e+08   2.50830290e+08   2.22750371e+08   6.55260000e+00]
 [  6.98080000e+04   2.08240000e+05   4.59300000e+03   8.82400000e-01]
 [  1.50889030e+07   1.73904450e+07   8.50541800e+06  -3.88770000e+00]
 [  2.28951300e+06   1.83712900e+06   2.88971000e+05   1.04380000e+00]
 [  2.51798530e+07   5.29915680e+07   3.31730740e+07   2.09450000e+00]
 [  3.27412000e+05   7.80088000e+05   2.91863000e+05   5.14150000e+00]
 [  3.29765270e+07   5.91443110e+07   4.92830000e+04   3.25700000e+0

In [4]:
import sklearn.cross_validation as cross_validation
import sklearn.metrics as metrics

#Define X, Y variables. Let's use columns 0 (2014) and 1 (2015) and the target y variable to be (2016)
X = aid[:, (0,1)]
y = aid[:,2]

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
#Now that we have the variables defined, let's try a linear regression classifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [22]:
from sklearn.linear_model import LinearRegression
import sklearn.linear_model as linear_model

from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)
print(regr.coef_)

[ 0.29782557  0.29001735]


In [24]:
#Now let's look at the mean square error of the linear regression model
np.mean((regr.predict(X_test)- y_test)**2)

7289594677306418.0

In [17]:
predicted_2016 = lr.predict(X_test)
predicted_2016

array([  1.46251016e+07,   9.67327317e+07,   5.42930554e+06,
         1.49554707e+07,   2.80665126e+07,   1.55777799e+08,
         1.63194454e+07,   6.60433980e+07,   2.90440386e+07,
         4.29085733e+07,   3.67993472e+07,   1.75662903e+07,
         4.03690615e+08,   1.70099521e+07,   6.43802004e+07,
         1.35591936e+08,   5.41748751e+08,   4.49811954e+08,
         5.34544921e+06,   6.80219623e+06,   2.80007623e+07,
         1.28720487e+08,   9.83051206e+06,   1.23669414e+07,
         9.93554147e+06,   1.35513090e+08,   2.39682676e+07])

In [18]:
# print predicted values for 2016 side by side of the actual value

for i in range(len(y_test)):
    print (i)
    print(y_test[i:i+1],'----', predicted_2016[i:i+1])
    print ('*'*5)

0
[ 8505418.] ---- [ 14625101.5813588]
*****
1
[  1.87527162e+08] ---- [ 96732731.74869394]
*****
2
[ 90330.] ---- [ 5429305.54086936]
*****
3
[ 14881734.] ---- [ 14955470.73949112]
*****
4
[ 23697925.] ---- [ 28066512.63601375]
*****
5
[  2.22750371e+08] ---- [  1.55777799e+08]
*****
6
[ 9614173.] ---- [ 16319445.39430049]
*****
7
[  1.59935054e+08] ---- [ 66043397.99842994]
*****
8
[ 42846592.] ---- [ 29044038.62436408]
*****
9
[ 52439601.] ---- [ 42908573.27011522]
*****
10
[ 12893047.] ---- [ 36799347.23802126]
*****
11
[ 18005091.] ---- [ 17566290.33534646]
*****
12
[  7.30911332e+08] ---- [  4.03690615e+08]
*****
13
[ 8047023.] ---- [ 17009952.14696326]
*****
14
[ 68299531.] ---- [ 64380200.38741232]
*****
15
[  1.62624011e+08] ---- [  1.35591936e+08]
*****
16
[  5.14068190e+08] ---- [  5.41748751e+08]
*****
17
[  6.52346033e+08] ---- [  4.49811954e+08]
*****
18
[ 45166.] ---- [ 5345449.21079158]
*****
19
[ 446355.] ---- [ 6802196.23187299]
*****
20
[ 23701622.] ---- [ 28000762.2

In [26]:
#Since Linear Regression is not an accurate predictor of economic aid in 2016 based on 2015 data, let's try a Logistic
#Regression classifier
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#Fit a Logistic Regression model to the data
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
print(logistic.coef_)

[[  1.53686755e-05  -7.20629698e-05]
 [  1.13314361e-07  -1.31994971e-05]
 [ -2.85371310e-05   6.15089083e-06]
 [  6.65012107e-09  -3.95916299e-07]
 [  1.37116193e-05  -6.48415538e-05]
 [ -3.20165790e-05  -8.46669628e-06]
 [ -2.95551033e-07   6.01608545e-08]
 [ -3.89851045e-06  -4.28213415e-07]
 [  9.77850767e-07  -4.84126620e-06]
 [  3.70117735e-07  -1.98914235e-06]
 [ -6.43770391e-06  -1.37209369e-06]
 [  2.99502960e-06  -1.43663745e-05]
 [ -3.09815963e-07  -7.74752484e-08]
 [ -8.54313338e-07  -4.01269005e-06]
 [ -8.69181123e-07   1.39886404e-07]
 [ -1.31094937e-07  -1.70698545e-06]
 [ -1.10453151e-05   2.33938357e-06]
 [ -7.34131529e-06   1.55922436e-06]
 [ -9.53772759e-06   2.01414651e-06]
 [ -1.33019562e-06  -3.24386632e-07]
 [ -1.99997678e-06  -1.15301078e-06]
 [ -1.28301271e-06  -9.62824050e-07]
 [  3.57967566e-08  -2.30569573e-07]
 [  1.50650697e-06  -7.26760782e-06]
 [ -7.49688783e-07   9.98281399e-08]
 [ -6.26658288e-07  -6.13125410e-07]
 [ -9.04410835e-07   1.58408919e-07]
 

In [28]:
#Now let's look at the mean square error of the linear regression model
np.mean((regr.predict(X_test)- y_test)**2)

7289594677306418.0

In [27]:
#Now let's look at accuracy of the Logistic Regression model
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, logistic.predict(X_test)))

#From these results, we see that there is no accuracy at using 2014 economic aid data to predict 2015 economic aid data.

0.0
